### ISSUE TITLE
Edge bridge not working in latest flutter version 3.19.x

### ISSUE THREAD

**Issue by AnanthanAn** [adobe/aepsdk_flutter#121]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk_flutter/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

Currently using AEP edge plugins to send analytics data to adobe. Implementation works fine on flutter version 3.7.x but after flutter upgrade to the latest version 3.19.x. Tried latest 4.0.1 version plugins but issue still exists

### Environment

[✓] Flutter (Channel stable, 3.19.6, on macOS 14.1.1 23B81 darwin-arm64 (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.67.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Comment by cacheung** [comment]
@AnanthanAn Is there any error you see for not working on 3.19.x?  Compile error?  The error is on flutter or native platforms?

**Comment by AnanthanAn** [comment]
no errors but its not initialising . i dont get any logs as well

**Comment by cacheung** [comment]
@AnanthanAn I saw you have a consultant working with you on this.  We will follow up there.

**Comment by cacheung** [comment]
Closing the ticket.  We will follow up through the consultant.
