### ISSUE TITLE
Could not find identity-3.0.1.jar (com.adobe.marketing.mobile:identity:3.0.1).

### ISSUE THREAD

**Issue by BolisettySujith** [adobe/aepsdk_flutter#126]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk_flutter/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

When I was adding the flutter_aep* packages in my flutter app, I was getting this error mentioning `Could not find identity-3.0.1.jar (com.adobe.marketing.mobile:identity:3.0.1).`

Below is the full logs of the error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':app:compileDebugKotlin'
   > Could not resolve all files for configuration ':app:debugCompileClasspath'.
      > Failed to transform identity-3.0.1.jar (com.adobe.marketing.mobile:identity:3.0.1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
         > Could not find identity-3.0.1.jar (com.adobe.marketing.mobile:identity:3.0.1).
           Searched in the following locations:
               https://jcenter.bintray.com/com/adobe/marketing/mobile/identity/3.0.1/identity-3.0.1.jar
      > Failed to transform lifecycle-3.0.1.jar (com.adobe.marketing.mobile:lifecycle:3.0.1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
         > Could not find lifecycle-3.0.1.jar (com.adobe.marketing.mobile:lifecycle:3.0.1).
           Searched in the following locations:
               https://jcenter.bintray.com/com/adobe/marketing/mobile/lifecycle/3.0.1/lifecycle-3.0.1.jar
      > Failed to transform core-3.0.1.jar (com.adobe.marketing.mobile:core:3.0.1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
         > Could not find core-3.0.1.jar (com.adobe.marketing.mobile:core:3.0.1).
           Searched in the following locations:
               https://jcenter.bintray.com/com/adobe/marketing/mobile/core/3.0.1/core-3.0.1.jar

```

it seems like it couldn't able to find the latest 3.0.1 version....

@cacheung  or anyone help me fixing the issue...?

### Environment

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.22000.2538], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.89.1)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.

### Steps to reproduce

1. Add flutter_aepcore package in pubspec.yaml
2. Run the app
3. This will be thrown

### Anything else?

I was thinking the 3.0.1 was released recently 6hrs ago, and it was not reflected in maven central but not sure. Please help me in giving me more information about it.

**Comment by cacheung** [comment]
Jcenter is deprecated long time ago.  We didn't post any Android libraries to there.
Can you check if you have any Jcenter() listed in build.gradle file?   If so, remove it.
e.g https://github.com/adobe/aepsdk_flutter/blob/main/example/android/build.gradle#L12

**Comment by BolisettySujith** [comment]
Thank you very much @cacheung , it solved the issue.
