### ISSUE TITLE
Future waiting infinite for method Identity.updateIdentities(identityMap)

### ISSUE THREAD

**Issue by dieg0omni** [adobe/aepsdk_flutter#128]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk_flutter/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

When i use:
await Identity.updateIdentities(identityMap) in IOS still waiting infinite
in android works fine the same code.

is correct use await for this future or i can omit that ?

### Environment

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.8, on macOS 15.0 24A335 darwin-arm64, locale es-CO)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.90.0)
[✓] Connected device (5 available)
[✓] Network resources

### Steps to reproduce

1. Import library version :
      flutter_aepassurance: ^4.0.1
      flutter_aepcore: ^4.0.1
      flutter_aepedgeidentity: ^4.0.1
2. Create a method and use await Identity.updateIdentities(identityMap)
3. You will se that never end thid method in IOS

### Current behavior

Waiting infinite in IOS.

### Expected behavior

Same behavior than android

**Comment by cdhoffmann** [comment]
Hey @dieg0omni, the `updateIdentities` API does not return a value. No need to await for it. Here is our [API reference doc](https://github.com/adobe/aepsdk_flutter/tree/main/plugins/flutter_aepedgeidentity#updateidentities) for this API.

**Comment by dieg0omni** [comment]
@cdhoffmann thx
