### ISSUE TITLE
Add "FullscreenMessageActivity" and "LocalNotificationHandler" to the AEPCore AndroidManifest.xml

### ISSUE THREAD

**Issue by cacheung** [adobe/aepsdk_flutter#7]
In AEPCore AndroidManifest file, we don't have "FullscreenMessageActivity" activity  and "LocalNotificationHandler" receiver.  They will be used by messaging, campaign, etc.
  
### Expected Behaviour

In  https://github.com/adobe/aepsdk_flutter/blob/main/plugins/flutter_aepcore/android/src/main/AndroidManifest.xml, include
```
<application>
        <activity
            android:name="com.adobe.marketing.mobile.FullscreenMessageActivity"
            android:exported="false" />
        <receiver
            android:name="com.adobe.marketing.mobile.LocalNotificationHandler"
            android:exported="false" />
 </application>
```

**Comment by praveek** [comment]
We don't have to add them to Core manifest. `FullscreenMessageActivity` has been removed from Android Mobile Core SDK v2.0. 
If an app depends on campaign/messaging/target, `LocalNotificationHandler` should be added directly to the app's manifest.
