### ISSUE TITLE
Upgrade AEPCore and AEPServices so as to include Privacy Manifests

### ISSUE THREAD

**Issue by jamieastley** [adobe/aepsdk_flutter#90]
### Expected Behaviour

[As per Apple's requirements](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests):

> Third-party SDKs need to provide their own privacy manifest files that record the types of data they collect. Your app’s privacy manifest file doesn’t need to cover data collected by third-party SDKs that your app links to.

It looks like this was addressed recently in the `aepsdk-core-ios` repo via: https://github.com/adobe/aepsdk-core-ios/pull/992, so the Flutter package should be updated to integrate the latest SDK changes to include the privacy manifests.

### Actual Behaviour

Privacy manifests are not currently present for iOS.

### Reproduce Scenario (including but not limited to)

- N/A

#### Steps to Reproduce

- N/A

#### Platform and Version

- iOS, flutter_aepcore: ^3.0.0

#### Sample Code that illustrates the problem

- N/A

#### Logs taken while reproducing problem

- N/A

**Comment by cdhoffmann** [comment]
@jamieastley Thank you for reporting. We are planning on releasing the native SDKs in the next couple of weeks, and then our Flutter and React-Native solutions will follow suit. Thank you for your patience.

**Comment by jamieastley** [comment]
@cdhoffmann having been almost a month since the last update, is there any further update to provide as to when the Flutter packages will be updated to cater for these fast approaching requirements?

**Comment by cdhoffmann** [comment]
@jamieastley The updates are being worked on as we speak. They will be released soon. Thank you for your patience.

**Comment by cdhoffmann** [comment]
@jamieastley The new versions have been released which include the privacy manifest. Closing now.
