### ISSUE TITLE
Document if this SDK supports Flutter Web

### ISSUE THREAD

**Issue by freemansoft** [adobe/aepsdk_flutter#99]
### Expected Behaviour

one ore more of the follwing
* aepsdk flutter supports flutter web, flutter build as a web app and an example is provided
* adobe does not support flutter web and documents it

### Actual Behaviour

No documentation found

### Reproduce Scenario (including but not limited to)

n/a

#### Steps to Reproduce

n/a

#### Platform and Version

n/a

#### Sample Code that illustrates the problem

n/a

#### Logs taken while reproducing problem

n/a

**Comment by cacheung** [comment]
According to the Project [readme](https://github.com/adobe/aepsdk_flutter?tab=readme-ov-file#about-this-project), This repository is a monorepo. It contains a collection of Adobe Experience Platform Mobile SDK Flutter plugins listed below. These plugins can be found in the [plugins](https://github.com/adobe/aepsdk_flutter/blob/main/plugins) directory.

The aepsdk_flutter supports mobile sdk Flutter plugins.  
We don't specifically call out the non-supported platforms including Flutter Web in the documentation.

**Comment by freemansoft** [comment]
People coming here may be Flutter-only teams and not previous Adobe mobile users. 

The README should point out that _no other Flutter platforms are supported or that Adobe metrics may be supported on one of the other 4 platforms using other SDKs

We had three people look at the docs without understanding what we needed to do for Adobe metrics for Flutter apps based on the platform.

**Comment by cacheung** [comment]
May I know what flutter platform you are looking for Adobe Analytics Metrics? 
We don't support Flutter Web in this repo.  This repo is for Mobile SDK only.  
Are you a new user or you have been using adobe Flutter Mobile SDK previously for Analytics?

**Comment by cacheung** [comment]
Add a note for supported platforms info to the main readme.
https://github.com/adobe/aepsdk_flutter?tab=readme-ov-file#aepsdk-flutter
```text
The Flutter plugins within this repository are specifically designed to support the Android and iOS platforms only.
```
